# Generated by Django 5.0.6 on 2024-05-10 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eShopApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eShopApp.product')),
            ],
        ),
    ]
