# Generated by Django 5.0.6 on 2024-05-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eShopApp', '0002_moreimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moreimages',
            options={'verbose_name': "Ko'proq rasm", 'verbose_name_plural': "Ko'proq rasmlar"},
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='comment', max_length=130),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
    ]
