# Generated by Django 5.0.6 on 2024-05-12 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eShopApp', '0003_alter_moreimages_options_comment_body_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_product', to='eShopApp.product'),
        ),
    ]
