# Generated by Django 5.0.6 on 2024-05-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eShopApp', '0005_remove_order_status_order_quantity_shipping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping',
            options={'verbose_name': 'Yetkazib berish', 'verbose_name_plural': 'Yetkazib berish'},
        ),
        migrations.AddField(
            model_name='shipping',
            name='adress',
            field=models.TextField(default='1', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='contact_for',
            field=models.CharField(default='2', max_length=20),
            preserve_default=False,
        ),
    ]
