# Generated by Django 3.2.15 on 2024-05-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eShopApp', '0006_alter_shipping_options_shipping_adress_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
