# Generated by Django 3.2.15 on 2024-05-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eShopApp', '0007_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='order',
        ),
        migrations.AddField(
            model_name='shipping',
            name='order',
            field=models.ManyToManyField(related_name='shipping_order', to='eShopApp.Order'),
        ),
    ]
