# Generated by Django 3.2.15 on 2024-05-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eShopApp', '0008_auto_20240513_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='total_price',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
