# Generated by Django 3.2.15 on 2024-05-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eShopApp', '0011_order_is_shipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='order',
            field=models.ManyToManyField(blank=True, related_name='shipping_order', to='eShopApp.Order'),
        ),
    ]
