# Generated by Django 3.2.15 on 2024-05-15 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eShopApp', '0012_alter_shipping_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
